### ISSUE TITLE
Installing www-m failes

### ISSUE THREAD

**Issue by PHPoenX** [radareorg/radare2-webui#161]
`.local/share/radare2/r2pm/git/radare2-webui/www/m/node_modules/.bin/yarn: Command not found`

npm12, opensuse tumbleweed, latest version of r2 and r2pm. Latest version of yarn is installed

**Comment by radare** [comment]
Yarn is dead. Npm should be used instead, feek free to send a pr fixing it

**Comment by trufae** [comment]
Fixed now
