### ISSUE TITLE
Choose one main WebUI, convert to TypeScript

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-webui#162]
Choose the only one WebUI, remove all others (they will stay in the git history anyway), and convert it to the TypeScript: https://www.tutorialsteacher.com/typescript/converting-javascript-to-typescript

**Comment by radare** [comment]
If its hard to find someone motivated to do js... cant imagine someone doing typescript. Also, about which one to pick. That was already drcided 4 years ago. The material one
