### ISSUE TITLE
Add text-to-speech support

### ISSUE THREAD

**Issue by radare** [radareorg/radare2-webui#71]
To read fortunes
To read status messages
...

configure voice in settings

**Comment by radare** [comment]
Initial work is done here: https://github.com/radare/radare2-webui/commit/a95377f3459c98f7a70b4572fe6b000e4c9fc34d

**Comment by radare** [comment]
Let's consider it done.

**Comment by radare** [comment]
maybe add a "TTS" button inside the Comments -> Notes panel too

**Comment by trufae** [comment]
It's done and totally unnecessary :D
